//! `gsx-faucet` binary — axum HTTP service.
//!
//! ## Endpoints
//!
//! - `POST /faucet { "address": "0x..." }` — issue one drip.
//!   Returns `{ "tx_hash": "0x...", "amount": <u128> }` on success;
//!   HTTP 429 with `{ "error": "rate limited", "retry_after_ms": N }`
//!   on per-IP bucket exhaustion; 503 with `{ "error": "empty" }` if
//!   the faucet's own wallet is drained; 400 on a malformed address.
//! - `GET /health` — returns 200 with the faucet's address +
//!   signer-pubkey-hash if the wallet has at least one drip's worth
//!   of balance; 503 otherwise. Used by the G6 monitoring alarm.
//!
//! ## Config
//!
//! All knobs are CLI flags or env vars. Defaults target a devnet
//! deployment on a single t4g.small EC2 instance behind an ALB.

use std::{
    fs,
    net::{IpAddr, SocketAddr},
    sync::Arc,
};

use axum::{
    extract::{ConnectInfo, Json, State},
    http::StatusCode,
    response::IntoResponse,
    routing::{get, post},
    Router,
};
use clap::Parser;
use gsx_crypto::mldsa;
use gsx_faucet::{Faucet, FaucetError};
use serde::{Deserialize, Serialize};
use tracing::{info, warn};
use tracing_subscriber::EnvFilter;

#[derive(Parser, Debug, Clone)]
#[command(name = "gsx-faucet", about = "Devnet test-token faucet HTTP service")]
struct Args {
    /// JSON-RPC URL of the devnet (e.g.
    /// `https://rpc.devnet.gsx.globalsettlement.com`).
    #[arg(long, env = "GSX_FAUCET_RPC_URL")]
    rpc_url: String,

    /// Path to the faucet's ML-DSA-65 secret key (binary, 4032 B).
    /// Generated by `scripts/devnet/gen-genesis.py` into
    /// `target/devnet/keys/faucet/mldsa.sk`.
    #[arg(long, env = "GSX_FAUCET_SK_PATH")]
    secret_key_path: String,

    /// Path to the faucet's ML-DSA-65 public key (binary, 1952 B).
    #[arg(long, env = "GSX_FAUCET_PK_PATH")]
    public_key_path: String,

    /// Faucet's 20-byte address as a 0x-prefixed hex string. MUST
    /// match the `faucet_address` seeded in the devnet genesis
    /// pre-balances. If unset, derived from the public key via the
    /// canonical recipe — but trust the explicit value when in
    /// doubt; the pre-balance must reference the same address.
    #[arg(long, env = "GSX_FAUCET_ADDRESS")]
    faucet_address: Option<String>,

    /// Network identifier baked into the signing digest. MUST match
    /// the devnet genesis's `network_id`.
    #[arg(long, default_value = "gsx-devnet", env = "GSX_FAUCET_NETWORK_ID")]
    network_id: String,

    /// Amount in GSX (u128) handed out per drip. Default: 100 GSX —
    /// enough for a few hundred test transfers without re-faucet.
    #[arg(long, default_value_t = 100, env = "GSX_FAUCET_DRIP_AMOUNT")]
    drip_amount: u128,

    /// Per-IP token-bucket capacity. The N+1th drip request from one
    /// IP within the refill window is rejected with HTTP 429.
    /// Default: 5 (enough to bootstrap a few addresses from one
    /// machine, tight enough to discourage scripted abuse).
    #[arg(long, default_value_t = 5, env = "GSX_FAUCET_BUCKET_CAPACITY")]
    bucket_capacity: u64,

    /// Per-IP refill rate in tokens per hour. Default: 5/hour — at
    /// steady state, one IP gets ~120 drips/day max.
    #[arg(long, default_value_t = 5, env = "GSX_FAUCET_BUCKET_REFILL_PER_HOUR")]
    bucket_refill_per_hour: u64,

    /// TCP bind address.
    #[arg(long, default_value = "0.0.0.0:8080", env = "GSX_FAUCET_BIND")]
    bind: SocketAddr,
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| EnvFilter::new("gsx_faucet=info,axum=warn,tower_http=info")),
        )
        .init();

    let args = Args::parse();

    let sk_bytes = fs::read(&args.secret_key_path)?;
    let pk_bytes = fs::read(&args.public_key_path)?;
    let secret_key = mldsa::SecretKey::from_bytes(&sk_bytes).map_err(|e| {
        anyhow::anyhow!(
            "invalid ML-DSA secret key at {}: {}",
            args.secret_key_path,
            e
        )
    })?;
    let public_key = mldsa::PublicKey::from_bytes(&pk_bytes).map_err(|e| {
        anyhow::anyhow!(
            "invalid ML-DSA public key at {}: {}",
            args.public_key_path,
            e
        )
    })?;

    let faucet_address = match args.faucet_address.as_ref() {
        Some(hex) => parse_address(hex).map_err(|e| anyhow::anyhow!("--faucet-address: {}", e))?,
        None => {
            // Derive from pubkey via the canonical recipe. Loud warn
            // so operators know they're relying on it.
            warn!(
                "no --faucet-address supplied; deriving from pubkey. \
                 If the genesis pre-balance used a different recipe \
                 the faucet will see zero balance."
            );
            gsx_faucet::address_from_pubkey(&public_key)
        }
    };

    // Convert bucket refill from per-hour (operator-friendly) to
    // per-sec (LeakyBucket's internal unit). Round up so we don't
    // silently throttle harder than the operator asked.
    let refill_per_sec = ((args.bucket_refill_per_hour as f64) / 3600.0).ceil() as u64;
    if refill_per_sec == 0 {
        warn!(
            "bucket refill rounds to 0 tokens/sec; raising to 1 — set \
             --bucket-refill-per-hour ≥ 3600 to avoid this."
        );
    }
    let refill_per_sec = refill_per_sec.max(1);

    let faucet = Arc::new(Faucet::new(
        args.rpc_url.clone(),
        secret_key,
        public_key,
        faucet_address,
        args.network_id.clone(),
        args.drip_amount,
        args.bucket_capacity,
        refill_per_sec,
    ));

    info!(
        rpc_url = %args.rpc_url,
        network_id = %args.network_id,
        drip_amount = args.drip_amount,
        faucet_address = %format!("0x{}", hex::encode(faucet.address())),
        bucket_capacity = args.bucket_capacity,
        refill_per_hour = args.bucket_refill_per_hour,
        "faucet: starting"
    );

    let app = Router::new()
        .route("/faucet", post(handle_drip))
        .route("/health", get(handle_health))
        .with_state(faucet);

    let listener = tokio::net::TcpListener::bind(args.bind).await?;
    let actual = listener.local_addr()?;
    info!(addr = %actual, "faucet: HTTP server bound");
    axum::serve(
        listener,
        app.into_make_service_with_connect_info::<SocketAddr>(),
    )
    .await?;
    Ok(())
}

#[derive(Debug, Deserialize)]
struct DripRequest {
    address: String,
}

#[derive(Debug, Serialize)]
struct ErrorBody {
    error: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    retry_after_ms: Option<u64>,
}

async fn handle_drip(
    State(faucet): State<Arc<Faucet>>,
    ConnectInfo(peer): ConnectInfo<SocketAddr>,
    Json(req): Json<DripRequest>,
) -> impl IntoResponse {
    let peer_ip: IpAddr = peer.ip();
    let address = match parse_address(&req.address) {
        Ok(a) => a,
        Err(e) => {
            return (
                StatusCode::BAD_REQUEST,
                Json(ErrorBody {
                    error: e,
                    retry_after_ms: None,
                }),
            )
                .into_response();
        }
    };

    match faucet.drip(peer_ip, address).await {
        Ok(ack) => (StatusCode::OK, Json(ack)).into_response(),
        Err(FaucetError::RateLimited(retry_after_ms)) => (
            StatusCode::TOO_MANY_REQUESTS,
            Json(ErrorBody {
                error: "rate limited".into(),
                retry_after_ms: Some(retry_after_ms),
            }),
        )
            .into_response(),
        Err(FaucetError::Empty) => (
            StatusCode::SERVICE_UNAVAILABLE,
            Json(ErrorBody {
                error: "faucet wallet empty".into(),
                retry_after_ms: None,
            }),
        )
            .into_response(),
        Err(FaucetError::InvalidAddress(e)) => (
            StatusCode::BAD_REQUEST,
            Json(ErrorBody {
                error: e,
                retry_after_ms: None,
            }),
        )
            .into_response(),
        Err(other) => {
            warn!(error = %other, "faucet drip failed");
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(ErrorBody {
                    error: other.to_string(),
                    retry_after_ms: None,
                }),
            )
                .into_response()
        }
    }
}

#[derive(Debug, Serialize)]
struct HealthBody {
    address: String,
    signer_pubkey_hash: String,
    alive: bool,
}

async fn handle_health(State(faucet): State<Arc<Faucet>>) -> impl IntoResponse {
    let alive = faucet.is_alive().await;
    let body = HealthBody {
        address: format!("0x{}", hex::encode(faucet.address())),
        signer_pubkey_hash: format!("0x{}", hex::encode(faucet.signer_pubkey_hash())),
        alive,
    };
    let status = if alive {
        StatusCode::OK
    } else {
        StatusCode::SERVICE_UNAVAILABLE
    };
    (status, Json(body))
}

fn parse_address(raw: &str) -> Result<[u8; 20], String> {
    let trimmed = raw
        .strip_prefix("0x")
        .or_else(|| raw.strip_prefix("0X"))
        .unwrap_or(raw);
    let bytes = hex::decode(trimmed).map_err(|e| format!("hex: {}", e))?;
    bytes
        .as_slice()
        .try_into()
        .map_err(|_| format!("expected 20-byte address, got {} bytes", bytes.len()))
}
