//! Cross-checks the pure-Rust (RustCrypto) ML-DSA-65 / ML-KEM-768 backends
//! against the PQClean bindings they replaced.
//!
//! Self-consistency is not enough here: these primitives sign consensus messages
//! and seal session keys, so the migration is only safe if the new code produces
//! and accepts *exactly* the byte strings the old code did. Concretely, keys
//! already in validator keystores must still load, and signatures already on
//! chain must still verify.
//!
//! `pqcrypto-*` is a dev-dependency only and is not linked into any shipped
//! artifact. These tests exist so the crates can be dropped entirely once this
//! has held for a release.

use pqcrypto_mlkem::mlkem768 as pq_kem;
use pqcrypto_traits::kem::{
    Ciphertext as _, PublicKey as _, SecretKey as _, SharedSecret as _,
};
use pqcrypto_traits::sign::{DetachedSignature as _, PublicKey as _, SecretKey as _};
use pqcrypto_mldsa::mldsa65 as pq_dsa;

use suwappu_crypto::{mldsa, mlkem};

// ---------------------------------------------------------------- ML-DSA-65

#[test]
fn mldsa_encoding_sizes_match_fips204() {
    let (pk, sk) = mldsa::keypair();
    assert_eq!(pk.as_bytes().len(), mldsa::PUBLIC_KEY_LEN);
    assert_eq!(sk.as_bytes().len(), mldsa::SECRET_KEY_LEN);
    let sig = mldsa::sign(b"m", &sk).unwrap();
    assert_eq!(sig.as_bytes().len(), mldsa::SIGNATURE_LEN);

    // ...and match what PQClean produced, so nothing stored changes shape.
    let (pq_pk, pq_sk) = pq_dsa::keypair();
    assert_eq!(pq_pk.as_bytes().len(), mldsa::PUBLIC_KEY_LEN);
    assert_eq!(pq_sk.as_bytes().len(), mldsa::SECRET_KEY_LEN);
}

#[test]
fn signature_made_by_rustcrypto_verifies_under_pqclean() {
    let (pk, sk) = mldsa::keypair();
    let msg = b"suwappu dag l1 attestation";

    let sig = mldsa::sign(msg, &sk).unwrap();

    let pq_pk = pq_dsa::PublicKey::from_bytes(pk.as_bytes()).unwrap();
    let pq_sig = pq_dsa::DetachedSignature::from_bytes(sig.as_bytes()).unwrap();
    pq_dsa::verify_detached_signature(&pq_sig, msg, &pq_pk)
        .expect("PQClean must accept a signature made by the pure-Rust backend");
}

#[test]
fn signature_made_by_pqclean_verifies_under_rustcrypto() {
    // This is the one that matters for anything already on chain.
    let (pq_pk, pq_sk) = pq_dsa::keypair();
    let msg = b"historic attestation";
    let pq_sig = pq_dsa::detached_sign(msg, &pq_sk);

    let pk = mldsa::PublicKey::from_bytes(pq_pk.as_bytes()).unwrap();
    let sig = mldsa::Signature::from_bytes(pq_sig.as_bytes()).unwrap();
    mldsa::verify(msg, &sig, &pk)
        .expect("pure-Rust backend must accept a signature made by PQClean");
}

#[test]
fn pqclean_secret_key_is_usable_by_rustcrypto() {
    // Proves the 4032-byte expanded signing key is interpreted identically.
    // If this failed, every existing validator keystore would be dead.
    let (pq_pk, pq_sk) = pq_dsa::keypair();

    let sk = mldsa::SecretKey::from_bytes(pq_sk.as_bytes())
        .expect("an existing PQClean secret key must still load");
    let msg = b"signed with a key generated by the old implementation";
    let sig = mldsa::sign(msg, &sk).unwrap();

    let pq_pk_typed = pq_dsa::PublicKey::from_bytes(pq_pk.as_bytes()).unwrap();
    let pq_sig = pq_dsa::DetachedSignature::from_bytes(sig.as_bytes()).unwrap();
    pq_dsa::verify_detached_signature(&pq_sig, msg, &pq_pk_typed)
        .expect("signature must verify against the public key of the original keypair");
}

#[test]
fn attached_form_keeps_the_pqclean_layout() {
    // PQClean's signed-message form is `signature || message`. Anything that
    // parsed it before must keep parsing it.
    let (pk, sk) = mldsa::keypair();
    let msg = b"attached form";
    let signed = mldsa::sign_attached(msg, &sk).unwrap();

    assert_eq!(signed.len(), mldsa::SIGNATURE_LEN + msg.len());
    assert_eq!(&signed[mldsa::SIGNATURE_LEN..], msg);

    let recovered = mldsa::open_attached(&signed, &pk).unwrap();
    assert_eq!(recovered, msg);
}

#[test]
fn attached_form_rejects_a_tampered_message() {
    let (pk, sk) = mldsa::keypair();
    let mut signed = mldsa::sign_attached(b"attached form", &sk).unwrap();
    let last = signed.len() - 1;
    signed[last] ^= 0xFF;
    assert!(mldsa::open_attached(&signed, &pk).is_err());
}

// --------------------------------------------------------------- ML-KEM-768

#[test]
fn mlkem_encoding_sizes_match_fips203() {
    let (pk, sk) = mlkem::keypair();
    assert_eq!(pk.as_bytes().len(), mlkem::PUBLIC_KEY_LEN);
    assert_eq!(sk.as_bytes().len(), mlkem::SECRET_KEY_LEN);
    let (ct, _) = mlkem::encapsulate(&pk).unwrap();
    assert_eq!(ct.as_bytes().len(), mlkem::CIPHERTEXT_LEN);

    let (pq_pk, pq_sk) = pq_kem::keypair();
    assert_eq!(pq_pk.as_bytes().len(), mlkem::PUBLIC_KEY_LEN);
    assert_eq!(pq_sk.as_bytes().len(), mlkem::SECRET_KEY_LEN);
}

#[test]
fn rustcrypto_decapsulates_a_pqclean_ciphertext() {
    // An existing decapsulation key plus a ciphertext from a peer still running
    // the old implementation must yield the same shared secret.
    let (pq_pk, pq_sk) = pq_kem::keypair();
    let (pq_ss, pq_ct) = pq_kem::encapsulate(&pq_pk);

    let sk = mlkem::SecretKey::from_bytes(pq_sk.as_bytes())
        .expect("an existing PQClean decapsulation key must still load");
    let ct = mlkem::Ciphertext::from_bytes(pq_ct.as_bytes()).unwrap();

    let ss = mlkem::decapsulate(&ct, &sk).unwrap();
    assert_eq!(ss.as_bytes(), pq_ss.as_bytes());
}

#[test]
fn pqclean_decapsulates_a_rustcrypto_ciphertext() {
    // The reverse direction: a peer still on the old implementation must be able
    // to decapsulate what this one produces.
    let (pq_pk, pq_sk) = pq_kem::keypair();

    let pk = mlkem::PublicKey::from_bytes(pq_pk.as_bytes()).unwrap();
    let (ct, ss) = mlkem::encapsulate(&pk).unwrap();

    let pq_ct = pq_kem::Ciphertext::from_bytes(ct.as_bytes()).unwrap();
    let pq_ss = pq_kem::decapsulate(&pq_ct, &pq_sk);
    assert_eq!(pq_ss.as_bytes(), ss.as_bytes());
}
