#!/usr/bin/env bash
# Render per-region node.toml files from `terraform output` for the devnet.
# Run after `./scripts/deploy-aws.sh apply devnet` once EIPs have allocated;
# writes one node.toml per region under target/devnet/configs/<region>/node.toml,
# then uploads them to S3 so the bootstrap service on each EC2 picks them up.
#
# Diff vs. scripts/perf/render-configs.sh:
#   * Reads from terraform/devnet outputs (not perf).
#   * Renders rpc_listen + metrics_listen (perf leaves both off).
#   * Renders the per-IP rate-limit knobs to devnet-appropriate values.
#   * Auto-uploads to s3://<artifact_bucket>/configs/<region>/node.toml.
#
# Usage: scripts/devnet/render-configs.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TF="$ROOT/terraform/devnet"
OUT="$ROOT/target/devnet/configs"
CONSENSUS_PORT="${CONSENSUS_PORT:-9090}"
CLIENT_PORT="${CLIENT_PORT:-9091}"
RPC_PORT="${RPC_PORT:-9092}"
METRICS_PORT="${METRICS_PORT:-9093}"
ROUND_MS="${ROUND_MS:-250}"

if ! command -v jq >/dev/null 2>&1; then
  echo "error: jq required" >&2
  exit 1
fi

cd "$TF"
VALIDATORS_JSON="$(AWS_PROFILE=gsn terraform output -json validators)"
ARTIFACT_BUCKET="$(AWS_PROFILE=gsn terraform output -raw artifact_bucket)"

mkdir -p "$OUT"

regions=$(echo "$VALIDATORS_JSON" | jq -r 'keys[]')
for region in $regions; do
  authority_id=$(echo "$VALIDATORS_JSON" | jq -r --arg r "$region" '.[$r].authority_id')
  region_dir="$OUT/$region"
  mkdir -p "$region_dir"

  cfg="$region_dir/node.toml"
  {
    echo "# Auto-generated by scripts/devnet/render-configs.sh. Do not edit by hand."
    echo "self_id = \"$region\""
    echo "authority_id = $authority_id"
    echo "listen = \"0.0.0.0:$CONSENSUS_PORT\""
    echo "client_listen = \"0.0.0.0:$CLIENT_PORT\""
    echo "rpc_listen = \"0.0.0.0:$RPC_PORT\""
    echo "metrics_listen = \"127.0.0.1:$METRICS_PORT\""
    echo "round_ms = $ROUND_MS"
    echo "checkpoint_cadence_rounds = 1"
    echo "mldsa_secret_key_path = \"/var/lib/gsx/mldsa.sk\""
    echo "bls_secret_key_path = \"/var/lib/gsx/bls.sk\""
    echo "genesis_manifest_path = \"/etc/gsx/genesis.toml\""
    echo "event_log_path = \"/var/log/gsx/events.ndjson\""
    echo ""
    echo "# B1 + B2.1 hardening — devnet has a public RPC URL behind an ALB"
    echo "# + per-IP rate limiter. The defaults below are conservative for a"
    echo "# multi-tenant devnet where hundreds of dev shops may hit it."
    echo "max_client_connections = 256"
    echo "client_idle_timeout_ms = 30000"
    echo "client_per_ip_limit = 8"
    echo "rpc_per_ip_capacity = 60"
    echo "rpc_per_ip_refill_per_sec = 10"
    echo ""

    # Peer list = every region except this one.
    for peer in $regions; do
      if [ "$peer" = "$region" ]; then continue; fi
      peer_ip=$(echo "$VALIDATORS_JSON" | jq -r --arg r "$peer" '.[$r].public_ip')
      echo "[[peers]]"
      echo "id = \"$peer\""
      echo "addr = \"$peer_ip:$CONSENSUS_PORT\""
      echo ""
    done
  } > "$cfg"
  echo "wrote $cfg"

  AWS_PROFILE=gsn aws s3 cp "$cfg" "s3://$ARTIFACT_BUCKET/configs/$region/node.toml" \
    --region us-east-1
done

echo ""
echo "Configs uploaded to s3://$ARTIFACT_BUCKET/configs/<region>/node.toml"
echo "Restart validators to pick up: aws ssm send-command --instance-ids <id> \\"
echo "    --document-name AWS-RunShellScript \\"
echo "    --parameters 'commands=[\"systemctl restart gsx-bootstrap gsx-node\"]'"
