#!/usr/bin/env bash
# Render per-region testnet node.toml files from terraform output.
# Forked from scripts/devnet/render-configs.sh. Diffs:
#   * Reads from terraform/testnet outputs.
#   * 7 regions instead of 4 (more peer entries per file).
#   * No other behavior change — the rate-limit + RPC + metrics
#     knobs are identical to devnet's posture.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TF="$ROOT/terraform/testnet"
OUT="$ROOT/target/testnet/configs"
CONSENSUS_PORT="${CONSENSUS_PORT:-9090}"
CLIENT_PORT="${CLIENT_PORT:-9091}"
RPC_PORT="${RPC_PORT:-9092}"
METRICS_PORT="${METRICS_PORT:-9093}"
ROUND_MS="${ROUND_MS:-250}"

if ! command -v jq >/dev/null 2>&1; then
  echo "error: jq required" >&2
  exit 1
fi

cd "$TF"
VALIDATORS_JSON="$(AWS_PROFILE=gsn terraform output -json validators)"
ARTIFACT_BUCKET="$(AWS_PROFILE=gsn terraform output -raw artifact_bucket)"

mkdir -p "$OUT"

regions=$(echo "$VALIDATORS_JSON" | jq -r 'keys[]')
for region in $regions; do
  authority_id=$(echo "$VALIDATORS_JSON" | jq -r --arg r "$region" '.[$r].authority_id')
  region_dir="$OUT/$region"
  mkdir -p "$region_dir"

  cfg="$region_dir/node.toml"
  {
    echo "# Auto-generated by scripts/testnet/render-configs.sh. Do not edit by hand."
    echo "self_id = \"$region\""
    echo "authority_id = $authority_id"
    echo "listen = \"0.0.0.0:$CONSENSUS_PORT\""
    echo "client_listen = \"0.0.0.0:$CLIENT_PORT\""
    echo "rpc_listen = \"0.0.0.0:$RPC_PORT\""
    echo "metrics_listen = \"127.0.0.1:$METRICS_PORT\""
    echo "round_ms = $ROUND_MS"
    echo "checkpoint_cadence_rounds = 1"
    echo "mldsa_secret_key_path = \"/var/lib/suwappu/mldsa.sk\""
    echo "bls_secret_key_path = \"/var/lib/suwappu/bls.sk\""
    echo "genesis_manifest_path = \"/etc/suwappu/genesis.toml\""
    echo "event_log_path = \"/var/log/suwappu/events.ndjson\""
    echo ""
    echo "# Testnet runs heavier than devnet — the rate-limit knobs"
    echo "# are bumped up so dApps doing 100-Hz polling don't trip them."
    echo "max_client_connections = 1024"
    echo "client_idle_timeout_ms = 30000"
    echo "client_per_ip_limit = 16"
    echo "rpc_per_ip_capacity = 240"
    echo "rpc_per_ip_refill_per_sec = 40"
    echo ""

    # Peer list = every seed region except this one. External
    # validators (Track B program) get added to peer lists via a
    # governance Intent + a follow-up render-configs run after they
    # commit their first cert.
    for peer in $regions; do
      if [ "$peer" = "$region" ]; then continue; fi
      peer_ip=$(echo "$VALIDATORS_JSON" | jq -r --arg r "$peer" '.[$r].public_ip')
      echo "[[peers]]"
      echo "id = \"$peer\""
      echo "addr = \"$peer_ip:$CONSENSUS_PORT\""
      echo ""
    done
  } > "$cfg"
  echo "wrote $cfg"

  AWS_PROFILE=gsn aws s3 cp "$cfg" "s3://$ARTIFACT_BUCKET/configs/$region/node.toml" \
    --region us-east-1
done

echo ""
echo "Configs uploaded to s3://$ARTIFACT_BUCKET/configs/<region>/node.toml"
echo "Restart validators to pick up:"
echo "  for id in \$(AWS_PROFILE=gsn terraform output -json validators | jq -r '.[].instance_id'); do"
echo "    aws ssm send-command --instance-ids \$id \\"
echo "        --document-name AWS-RunShellScript \\"
echo "        --parameters 'commands=[\"systemctl restart suwappu-bootstrap suwappu-node\"]' \\"
echo "        --profile gsn"
echo "  done"
