#!/usr/bin/env bash
# Non-docker local devnet for gsx-dag.
#
# Boots 4 validators with REAL ML-DSA-65 + BLS keypairs (no placeholder bytes).
# Requires: cargo +1.90, bash >= 4.
#
# Subcommands:
#   up    — build, generate real-key genesis, write configs, start cluster
#   down  — kill all gsx-node devnet processes
#   logs  — tail v0's event log (Ctrl-C to exit)
#   check — poll v0 JSON-RPC until alive or timeout
#
# Per-node logs: target/devnet-real/v{0..3}/gsx-node.log
# Event logs:    target/devnet-real/v{0..3}/events.ndjson
#
# Usage:
#   bash scripts/devnet-local-nodocker.sh up
#   bash scripts/devnet-local-nodocker.sh logs
#   bash scripts/devnet-local-nodocker.sh down

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

DEVNET_DIR="$REPO_ROOT/target/devnet-real"
BINARY="$REPO_ROOT/target/release/gsx-node"
KEYGEN="$REPO_ROOT/target/release/gsx-keygen"
NUM_NODES=4

# Bridge attestation config — fixed for local devnet wiring.
#
# oracle = deployed GsxDagQuorumHeaderOracle (suwappu-node devnet deploy addr).
# network_id = keccak256("suwappu-perf-7r") = DEFAULT_BRIDGE_NETWORK_ID in daemon.rs.
#   byte-for-byte: 0xff431b3851ff00be6b5a4bd9b67e7d4118300693937865dfe75847dfd7cdd78a
BRIDGE_ORACLE="0xe7f1725e7734ce288f8367e1bb143e90bb3f0512"
BRIDGE_NETWORK_ID="0xff431b3851ff00be6b5a4bd9b67e7d4118300693937865dfe75847dfd7cdd78a"

cmd="${1:-up}"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

kill_cluster() {
    # Kill any gsx-node processes pointing at our devnet config dir.
    pkill -f "gsx-node --config $DEVNET_DIR" 2>/dev/null || true
}

wait_rpc_alive() {
    local port="$1"
    local attempts=0
    local max_attempts=60
    echo "  waiting for v0 JSON-RPC on port $port ..."
    while [[ $attempts -lt $max_attempts ]]; do
        if curl -sfX POST "http://127.0.0.1:$port" \
             -H 'content-type: application/json' \
             -d '{"jsonrpc":"2.0","id":1,"method":"gsx_getEpoch","params":null}' \
             >/dev/null 2>&1; then
            echo "  v0 JSON-RPC alive at http://127.0.0.1:$port"
            return 0
        fi
        sleep 1
        attempts=$((attempts + 1))
    done
    echo "  ERROR: v0 JSON-RPC did not respond within ${max_attempts}s"
    return 1
}

# ---------------------------------------------------------------------------
# Subcommands
# ---------------------------------------------------------------------------

case "$cmd" in
up)
    echo "==> Building gsx-node + gsx-keygen (release)..."
    cargo +1.90 build --release -p gsx-node
    echo

    echo "==> Stopping any existing devnet processes..."
    kill_cluster
    sleep 0.5

    echo "==> Generating real-key genesis (${NUM_NODES} nodes) under ${DEVNET_DIR} ..."
    mkdir -p "$DEVNET_DIR"
    "$KEYGEN" \
        --num-nodes "$NUM_NODES" \
        --out-dir "$DEVNET_DIR" \
        --network-id gsx-devnet-local \
        --stake-gsx 150000
    echo

    echo "==> Writing per-validator node.toml configs..."
    for i in 0 1 2 3; do
        VDIR="$DEVNET_DIR/v${i}"
        # Port scheme: v<i> uses listen=9090+100*i, client=9091+100*i, rpc=9092+100*i
        LISTEN_PORT=$((9090 + i * 100))
        CLIENT_PORT=$((9091 + i * 100))
        RPC_PORT=$((9092 + i * 100))

        cat > "$VDIR/node.toml" <<TOML
# Auto-generated by scripts/devnet-local-nodocker.sh
self_id = "v${i}"
authority_id = ${i}
listen = "127.0.0.1:${LISTEN_PORT}"
client_listen = "127.0.0.1:${CLIENT_PORT}"
rpc_listen = "127.0.0.1:${RPC_PORT}"
round_ms = 250
checkpoint_cadence_rounds = 1
mldsa_secret_key_path = "${VDIR}/mldsa.sk"
bls_secret_key_path = "${VDIR}/bls.sk"
genesis_manifest_path = "${DEVNET_DIR}/genesis.toml"
event_log_path = "${VDIR}/events.ndjson"

bridge_oracle_address = "${BRIDGE_ORACLE}"
bridge_network_id = "${BRIDGE_NETWORK_ID}"

max_client_connections = 256
client_idle_timeout_ms = 30000
client_per_ip_limit = 8

TOML

        # Append peers (everyone except self).
        for j in 0 1 2 3; do
            if [[ "$j" != "$i" ]]; then
                PEER_PORT=$((9090 + j * 100))
                cat >> "$VDIR/node.toml" <<TOML
[[peers]]
id = "v${j}"
addr = "127.0.0.1:${PEER_PORT}"
TOML
            fi
        done
        echo "    v${i}: listen=${LISTEN_PORT} client=${CLIENT_PORT} rpc=${RPC_PORT}"
    done
    echo

    echo "==> Starting ${NUM_NODES}-node cluster in background..."
    for i in 0 1 2 3; do
        VDIR="$DEVNET_DIR/v${i}"
        LOG="$VDIR/gsx-node.log"
        RUST_LOG=info "$BINARY" --config "$VDIR/node.toml" > "$LOG" 2>&1 &
        echo "    v${i} PID=$! log=${LOG}"
    done
    echo

    echo "==> Waiting for v0 RPC to come up (up to 60s)..."
    wait_rpc_alive 9092
    echo

    echo "==> Cluster up. Quick checks:"
    echo ""
    echo "  Epoch:       curl -s -X POST http://127.0.0.1:9092 \\"
    echo "                 -H 'content-type: application/json' \\"
    echo "                 -d '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"gsx_getEpoch\",\"params\":null}' | jq ."
    echo ""
    echo "  Block r=1:   curl -s -X POST http://127.0.0.1:9092 \\"
    echo "                 -H 'content-type: application/json' \\"
    echo "                 -d '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"gsx_getBlock\",\"params\":{\"round\":1}}' | jq ."
    echo ""
    echo "  Attestation: curl -s -X POST http://127.0.0.1:9092 \\"
    echo "                 -H 'content-type: application/json' \\"
    echo "                 -d '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"gsx_getHeaderAttestation\",\"params\":null}' | jq ."
    echo ""
    echo "Logs:  bash scripts/devnet-local-nodocker.sh logs"
    echo "Stop:  bash scripts/devnet-local-nodocker.sh down"
    ;;

down)
    echo "==> Stopping devnet..."
    kill_cluster
    echo "    done"
    ;;

logs)
    LOG="$DEVNET_DIR/v0/gsx-node.log"
    if [[ ! -f "$LOG" ]]; then
        echo "ERROR: no log at $LOG — run 'up' first"
        exit 1
    fi
    tail -f "$LOG"
    ;;

check)
    wait_rpc_alive 9092
    ;;

*)
    echo "Usage: $0 {up|down|logs|check}"
    exit 1
    ;;
esac
