#!/usr/bin/env bash
# Local-devnet bootstrap for suwappu-dag.
#
# Subcommands:
#   up      build the docker image + generate genesis + start 4 nodes
#   down    stop containers, keep target/devnet/
#   reset   stop containers AND wipe target/devnet/ + log volumes
#   logs    tail v0's stdout (Ctrl-C to exit)
#   curl    quick sanity-check that v0's JSON-RPC is alive
#
# Requirements: docker, docker compose v2, python3.
#
# See DEVNET.md for the full walkthrough.

set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$repo_root"

cmd=${1:-up}

case "$cmd" in
  up)
    echo "==> generating devnet genesis (4 nodes) under target/devnet/..."
    python3 scripts/gen-devnet-genesis.py --num-nodes 4 --out-dir target/devnet
    echo
    echo "==> writing per-validator node.toml from the genesis output..."
    for i in 0 1 2 3; do
      ip="172.30.0.1${i}"
      cat > "target/devnet/v${i}/node.toml" <<EOF
# Auto-generated by scripts/devnet-local.sh — re-run "up" to regenerate.
self_id = "v${i}"
authority_id = ${i}
listen = "0.0.0.0:9090"
client_listen = "0.0.0.0:9091"
rpc_listen = "0.0.0.0:9092"
round_ms = 250
checkpoint_cadence_rounds = 1
mldsa_secret_key_path = "/etc/suwappu/mldsa.sk"
bls_secret_key_path = "/etc/suwappu/bls.sk"
genesis_manifest_path = "/etc/suwappu/genesis.toml"
event_log_path = "/var/log/suwappu/events.ndjson"

# Track-B (B1) hardening defaults — overridable per-deployment.
max_client_connections = 256
client_idle_timeout_ms = 30000
client_per_ip_limit = 8

EOF
      # Append peers entries — everyone except self.
      for j in 0 1 2 3; do
        if [ "$j" != "$i" ]; then
          cat >> "target/devnet/v${i}/node.toml" <<EOF
[[peers]]
id = "v${j}"
addr = "172.30.0.1${j}:9090"
EOF
        fi
      done
    done
    echo
    echo "==> building suwappu-dag:devnet image (cold builds take ~10 min)..."
    docker compose build
    echo
    echo "==> starting cluster..."
    docker compose up -d
    echo
    echo "==> waiting for v0 to report a healthy JSON-RPC..."
    for _ in $(seq 1 30); do
      if curl -sfX POST http://127.0.0.1:9092 \
           -H 'content-type: application/json' \
           -d '{"jsonrpc":"2.0","id":1,"method":"suwappu_getEpoch","params":null}' \
           > /dev/null 2>&1; then
        echo "    v0 JSON-RPC live at http://127.0.0.1:9092"
        break
      fi
      sleep 2
    done
    echo
    echo "Cluster up. Quickstart:"
    echo "  ./scripts/devnet-local.sh curl       # sanity check"
    echo "  ./scripts/devnet-local.sh logs       # tail v0 stdout"
    echo "  ./scripts/devnet-local.sh down       # stop"
    echo "  ./scripts/devnet-local.sh reset      # wipe state"
    ;;

  down)
    docker compose down
    ;;

  reset)
    docker compose down -v
    rm -rf target/devnet
    echo "==> devnet reset; ready for ./scripts/devnet-local.sh up"
    ;;

  logs)
    docker compose logs -f v0
    ;;

  curl)
    curl -sX POST http://127.0.0.1:9092 \
      -H 'content-type: application/json' \
      -d '{"jsonrpc":"2.0","id":1,"method":"suwappu_getEpoch","params":null}' \
      | python3 -m json.tool
    ;;

  *)
    echo "usage: $0 {up|down|reset|logs|curl}" >&2
    exit 2
    ;;
esac
