#!/usr/bin/env bash
# Local-devnet bootstrap for gsx-dag.
#
# Subcommands (docker):
#   up      build the docker image + generate genesis + start 4 nodes
#   down    stop containers, keep target/devnet/
#   reset   stop containers AND wipe target/devnet/ + log volumes
#   logs    tail v0's stdout (Ctrl-C to exit)
#   curl    quick sanity-check that v0's JSON-RPC is alive
#   faucet  build + run gsx-faucet against the local cluster (foreground)
#
# Subcommands (baremetal — NO docker; runs N gsx-node processes on
# localhost with distinct per-node ports):
#   up-baremetal [N]      build gsx-node + genesis + launch N nodes (default 4)
#   down-baremetal        stop the baremetal nodes (keeps target/devnet/)
#   status-baremetal      per-node epoch/committed-round via JSON-RPC
#   logs-baremetal [i]    tail v<i>'s stdout (default v0)
#
# Requirements: python3 (+ docker/compose v2 for the docker subcommands;
# +cargo for the baremetal subcommands). The baremetal path exists for
# hosts without docker. Node v<i> binds rpc on 127.0.0.1:$((9092+10*i)).
#
# See DEVNET.md for the full walkthrough.

set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$repo_root"

cmd=${1:-up}

case "$cmd" in
  up)
    echo "==> building gsx-keygen (host-side, needed to mint the faucet ML-DSA key)..."
    cargo build --release -p gsx-crypto --bin gsx-keygen
    export PATH="$repo_root/target/release:$PATH"
    echo
    echo "==> generating devnet genesis (4 nodes) under target/devnet/..."
    python3 scripts/gen-devnet-genesis.py --num-nodes 4 --out-dir target/devnet
    echo
    echo "==> writing per-validator node.toml from the genesis output..."
    for i in 0 1 2 3; do
      ip="172.30.0.1${i}"
      cat > "target/devnet/v${i}/node.toml" <<EOF
# Auto-generated by scripts/devnet-local.sh — re-run "up" to regenerate.
self_id = "v${i}"
authority_id = ${i}
listen = "0.0.0.0:9090"
client_listen = "0.0.0.0:9091"
rpc_listen = "0.0.0.0:9092"
round_ms = 250
checkpoint_cadence_rounds = 1
mldsa_secret_key_path = "/etc/gsx/mldsa.sk"
bls_secret_key_path = "/etc/gsx/bls.sk"
genesis_manifest_path = "/etc/gsx/genesis.toml"
event_log_path = "/var/log/gsx/events.ndjson"

# Track-B (B1) hardening defaults — overridable per-deployment.
max_client_connections = 256
client_idle_timeout_ms = 30000
client_per_ip_limit = 8

EOF
      # Append peers entries — everyone except self.
      for j in 0 1 2 3; do
        if [ "$j" != "$i" ]; then
          cat >> "target/devnet/v${i}/node.toml" <<EOF
[[peers]]
id = "v${j}"
addr = "172.30.0.1${j}:9090"
EOF
        fi
      done
    done
    echo
    echo "==> building gsx-dag:devnet image (cold builds take ~10 min)..."
    docker compose build
    echo
    echo "==> starting cluster..."
    docker compose up -d
    echo
    echo "==> waiting for v0 to report a healthy JSON-RPC..."
    for _ in $(seq 1 30); do
      if curl -sfX POST http://127.0.0.1:9092 \
           -H 'content-type: application/json' \
           -d '{"jsonrpc":"2.0","id":1,"method":"gsx_getEpoch","params":null}' \
           > /dev/null 2>&1; then
        echo "    v0 JSON-RPC live at http://127.0.0.1:9092"
        break
      fi
      sleep 2
    done
    echo
    echo "Cluster up. Quickstart:"
    echo "  ./scripts/devnet-local.sh curl       # sanity check"
    echo "  ./scripts/devnet-local.sh faucet     # start the faucet (foreground)"
    echo "  ./scripts/devnet-local.sh logs       # tail v0 stdout"
    echo "  ./scripts/devnet-local.sh down       # stop"
    echo "  ./scripts/devnet-local.sh reset      # wipe state"
    ;;

  down)
    docker compose down
    ;;

  reset)
    # Tear down both flavors; ignore errors when one isn't in use.
    docker compose down -v 2>/dev/null || true
    # Stop any baremetal nodes by config-path cmdline match (covers both the
    # baremetal.pids-tracked processes and any orphaned by an unclean exit).
    pkill -f 'target/devnet/v.*/node.toml' 2>/dev/null || true
    rm -rf target/devnet
    echo "==> devnet reset; ready for ./scripts/devnet-local.sh {up|up-baremetal}"
    ;;

  logs)
    docker compose logs -f v0
    ;;

  curl)
    curl -sX POST http://127.0.0.1:9092 \
      -H 'content-type: application/json' \
      -d '{"jsonrpc":"2.0","id":1,"method":"gsx_getEpoch","params":null}' \
      | python3 -m json.tool
    ;;

  up-baremetal)
    # No-docker path: build gsx-node, generate genesis, write per-node
    # configs with DISTINCT localhost ports (the docker `up` reuses one
    # port set per container IP, which collides on a single host), then
    # launch N gsx-node processes detached. State lives under target/devnet/.
    n=${2:-4}
    bin="target/release/gsx-node"
    # gen-devnet-genesis.py invokes gsx-keygen to mint the faucet ML-DSA
    # key, so it must be on PATH before genesis generation.
    echo "==> building gsx-keygen + gsx-node (release)..."
    cargo build --release -p gsx-crypto --bin gsx-keygen
    cargo build --release -p gsx-node
    export PATH="$repo_root/target/release:$PATH"
    echo "==> generating devnet genesis ($n nodes) under target/devnet/..."
    python3 scripts/gen-devnet-genesis.py --num-nodes "$n" --out-dir target/devnet
    echo "==> writing baremetal node.toml (v<i> rpc = 127.0.0.1:\$((9092+10*i)))..."
    for i in $(seq 0 $((n - 1))); do
      listen=$((9090 + 10 * i)); client=$((9091 + 10 * i)); rpc=$((9092 + 10 * i))
      f="target/devnet/v${i}/node.toml"
      cat > "$f" <<EOF
self_id = "v${i}"
authority_id = ${i}
listen = "127.0.0.1:${listen}"
client_listen = "127.0.0.1:${client}"
rpc_listen = "127.0.0.1:${rpc}"
round_ms = 250
checkpoint_cadence_rounds = 1
mldsa_secret_key_path = "${repo_root}/target/devnet/v${i}/mldsa.sk"
bls_secret_key_path = "${repo_root}/target/devnet/v${i}/bls.sk"
genesis_manifest_path = "${repo_root}/target/devnet/genesis.toml"
event_log_path = "${repo_root}/target/devnet/v${i}/events.ndjson"
max_client_connections = 256
client_idle_timeout_ms = 30000
client_per_ip_limit = 8
EOF
      for j in $(seq 0 $((n - 1))); do
        if [ "$j" != "$i" ]; then
          printf '[[peers]]\nid = "v%s"\naddr = "127.0.0.1:%s"\n' "$j" "$((9090 + 10 * j))" >> "$f"
        fi
      done
    done
    echo "==> launching $n nodes (logs: target/devnet/v<i>/stdout.log)..."
    : > target/devnet/baremetal.pids
    for i in $(seq 0 $((n - 1))); do
      nohup "$bin" --config "target/devnet/v${i}/node.toml" \
        > "target/devnet/v${i}/stdout.log" 2>&1 &
      echo "$!" >> target/devnet/baremetal.pids
    done
    echo "==> waiting for v0's JSON-RPC..."
    rpc_up=0
    for _ in $(seq 1 30); do
      # Fail fast if a node we just launched has already exited — e.g. a
      # stale docker/baremetal cluster is still bound on these ports, so the
      # fresh binds failed. Without this, the curl probe below can succeed by
      # talking to the PRE-EXISTING service and falsely report the cluster up.
      dead=""
      while read -r pid; do
        kill -0 "$pid" 2> /dev/null || dead="$dead $pid"
      done < target/devnet/baremetal.pids
      if [ -n "$dead" ]; then
        echo "ERROR: launched node(s) exited (pid:$dead) — ports are likely" >&2
        echo "       already bound by a stale cluster. Run 'down-baremetal'" >&2
        echo "       first, then retry. Last lines of v0's log:" >&2
        tail -n 20 target/devnet/v0/stdout.log >&2 2> /dev/null || true
        exit 1
      fi
      if curl -sfX POST http://127.0.0.1:9092 \
           -H 'content-type: application/json' \
           -d '{"jsonrpc":"2.0","id":1,"method":"gsx_getEpoch","params":null}' \
           > /dev/null 2>&1; then
        echo "    v0 JSON-RPC live at http://127.0.0.1:9092"
        rpc_up=1
        break
      fi
      sleep 1
    done
    if [ "$rpc_up" -ne 1 ]; then
      echo "ERROR: v0 JSON-RPC did not come up within 30s (nodes alive but not" >&2
      echo "       serving). Check target/devnet/v0/stdout.log." >&2
      exit 1
    fi
    echo
    echo "Baremetal cluster up ($n nodes)."
    echo "  ./scripts/devnet-local.sh status-baremetal"
    echo "  ./scripts/devnet-local.sh logs-baremetal [i]"
    echo "  ./scripts/devnet-local.sh down-baremetal"
    ;;

  down-baremetal)
    if [ -f target/devnet/baremetal.pids ]; then
      while read -r pid; do
        # Only signal the pid if it's still OUR gsx-node. A stale pidfile
        # (after a reboot or an unclean exit) can list pids the OS has since
        # reused for unrelated processes — match the config-path cmdline
        # before SIGTERM so we never kill a bystander.
        if ps -p "$pid" -o command= 2> /dev/null | grep -q 'target/devnet/v.*/node.toml'; then
          kill "$pid" 2> /dev/null || true
        fi
      done < target/devnet/baremetal.pids
      rm -f target/devnet/baremetal.pids
    fi
    # Belt-and-suspenders: also match by config path in case the pid file
    # is stale (e.g. a prior run was killed without `down-baremetal`).
    pkill -f 'target/devnet/v.*/node.toml' 2> /dev/null || true
    echo "==> baremetal nodes stopped (state kept under target/devnet/)."
    ;;

  status-baremetal)
    for d in target/devnet/v*/; do
      [ -d "$d" ] || continue
      i=$(basename "$d" | tr -dc '0-9')
      rpc=$((9092 + 10 * i))
      printf 'v%s (rpc %s): ' "$i" "$rpc"
      curl -sX POST "http://127.0.0.1:${rpc}" \
        -H 'content-type: application/json' \
        -d '{"jsonrpc":"2.0","id":1,"method":"gsx_getEpoch","params":null}' 2> /dev/null \
        | python3 -c 'import sys,json;d=json.load(sys.stdin).get("result",{});print("epoch",d.get("current"),"committed_round",d.get("latest_committed_round"))' 2> /dev/null \
        || echo "(no response)"
    done
    ;;

  logs-baremetal)
    i=${2:-0}
    tail -f "target/devnet/v${i}/stdout.log"
    ;;

  faucet)
    if [ ! -f target/devnet/faucet/mldsa.sk ]; then
      echo "error: target/devnet/faucet/mldsa.sk not found." >&2
      echo "       Run ./scripts/devnet-local.sh up first." >&2
      exit 2
    fi
    echo "==> building gsx-faucet..."
    cargo build --release -p gsx-faucet
    network_id=$(awk -F'"' '/^network_id = / { print $2; exit }' target/devnet/genesis.toml)
    faucet_addr=$(cat target/devnet/faucet/address.hex)
    echo
    echo "==> starting faucet on 127.0.0.1:8080"
    echo "    network_id     = ${network_id}"
    echo "    faucet address = ${faucet_addr}"
    echo "    rpc            = http://127.0.0.1:9092"
    echo
    exec ./target/release/gsx-faucet \
      --rpc-url http://127.0.0.1:9092 \
      --secret-key-path target/devnet/faucet/mldsa.sk \
      --public-key-path target/devnet/faucet/mldsa.pk \
      --network-id "${network_id}" \
      --bind 127.0.0.1:8080
    ;;

  *)
    echo "usage: $0 {up|down|reset|logs|curl|faucet|up-baremetal|down-baremetal|status-baremetal|logs-baremetal}" >&2
    exit 2
    ;;
esac
