#!/usr/bin/env bash
# Local-devnet bootstrap for gsx-dag.
#
# Subcommands:
#   up            build the docker image + generate genesis + start 4 nodes
#   up-baremetal  same as `up` but no docker — 4 gsx-node processes on loopback
#   down          stop containers, keep target/devnet/
#   down-baremetal stop the bare-metal processes via target/devnet/v*.pid
#   reset         stop containers AND wipe target/devnet/ + log volumes
#   logs          tail v0's stdout (Ctrl-C to exit; docker path only)
#   logs-baremetal tail target/devnet/v0.log
#   curl          quick sanity-check that v0's JSON-RPC is alive
#   faucet        build + run gsx-faucet against the local cluster (foreground)
#
# Requirements: python3, cargo. Docker path additionally needs docker compose v2.
#
# See DEVNET.md for the full walkthrough.

set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$repo_root"

cmd=${1:-up}

case "$cmd" in
  up)
    echo "==> building gsx-keygen (host-side, needed to mint the faucet ML-DSA key)..."
    cargo build --release -p gsx-crypto --bin gsx-keygen
    export PATH="$repo_root/target/release:$PATH"
    echo
    echo "==> generating devnet genesis (4 nodes) under target/devnet/..."
    python3 scripts/gen-devnet-genesis.py --num-nodes 4 --out-dir target/devnet
    echo
    echo "==> writing per-validator node.toml from the genesis output..."
    for i in 0 1 2 3; do
      ip="172.30.0.1${i}"
      cat > "target/devnet/v${i}/node.toml" <<EOF
# Auto-generated by scripts/devnet-local.sh — re-run "up" to regenerate.
self_id = "v${i}"
authority_id = ${i}
listen = "0.0.0.0:9090"
client_listen = "0.0.0.0:9091"
rpc_listen = "0.0.0.0:9092"
round_ms = 250
checkpoint_cadence_rounds = 1
mldsa_secret_key_path = "/etc/gsx/mldsa.sk"
bls_secret_key_path = "/etc/gsx/bls.sk"
genesis_manifest_path = "/etc/gsx/genesis.toml"
event_log_path = "/var/log/gsx/events.ndjson"

# Track-B (B1) hardening defaults — overridable per-deployment.
max_client_connections = 256
client_idle_timeout_ms = 30000
client_per_ip_limit = 8

EOF
      # Append peers entries — everyone except self.
      for j in 0 1 2 3; do
        if [ "$j" != "$i" ]; then
          cat >> "target/devnet/v${i}/node.toml" <<EOF
[[peers]]
id = "v${j}"
addr = "172.30.0.1${j}:9090"
EOF
        fi
      done
    done
    echo
    echo "==> building gsx-dag:devnet image (cold builds take ~10 min)..."
    docker compose build
    echo
    echo "==> starting cluster..."
    docker compose up -d
    echo
    echo "==> waiting for v0 to report a healthy JSON-RPC..."
    for _ in $(seq 1 30); do
      if curl -sfX POST http://127.0.0.1:9092 \
           -H 'content-type: application/json' \
           -d '{"jsonrpc":"2.0","id":1,"method":"gsx_getEpoch","params":null}' \
           > /dev/null 2>&1; then
        echo "    v0 JSON-RPC live at http://127.0.0.1:9092"
        break
      fi
      sleep 2
    done
    echo
    echo "Cluster up. Quickstart:"
    echo "  ./scripts/devnet-local.sh curl       # sanity check"
    echo "  ./scripts/devnet-local.sh faucet     # start the faucet (foreground)"
    echo "  ./scripts/devnet-local.sh logs       # tail v0 stdout"
    echo "  ./scripts/devnet-local.sh down       # stop"
    echo "  ./scripts/devnet-local.sh reset      # wipe state"
    ;;

  down)
    docker compose down
    ;;

  reset)
    # Tear down both flavors; ignore errors when one isn't in use.
    docker compose down -v 2>/dev/null || true
    for i in 0 1 2 3; do
      pidfile="target/devnet/v${i}.pid"
      if [ -f "$pidfile" ]; then
        kill "$(cat "$pidfile")" 2>/dev/null || true
        rm -f "$pidfile"
      fi
    done
    rm -rf target/devnet
    echo "==> devnet reset; ready for ./scripts/devnet-local.sh {up|up-baremetal}"
    ;;

  logs)
    docker compose logs -f v0
    ;;

  curl)
    curl -sX POST http://127.0.0.1:9092 \
      -H 'content-type: application/json' \
      -d '{"jsonrpc":"2.0","id":1,"method":"gsx_getEpoch","params":null}' \
      | python3 -m json.tool
    ;;

  up-baremetal)
    echo "==> building gsx-keygen + gsx-node (host-side bare-metal mode)..."
    cargo build --release -p gsx-crypto --bin gsx-keygen
    cargo build --release -p gsx-node --bin gsx-node
    export PATH="$repo_root/target/release:$PATH"
    echo
    echo "==> generating devnet genesis (4 nodes) under target/devnet/..."
    python3 scripts/gen-devnet-genesis.py --num-nodes 4 --out-dir target/devnet
    echo
    echo "==> writing per-validator node.toml (loopback layout)..."
    # Port plan: v{N} listens on 127.0.0.1:9{N}90/91/92 for peer/client/rpc.
    # v0's RPC stays on :9092 so `curl` and `faucet` subcommands work unchanged.
    for i in 0 1 2 3; do
      base=9${i}
      cat > "target/devnet/v${i}/node.toml" <<EOF
# Auto-generated by scripts/devnet-local.sh (up-baremetal) — re-run to regenerate.
self_id = "v${i}"
authority_id = ${i}
listen = "127.0.0.1:${base}90"
client_listen = "127.0.0.1:${base}91"
rpc_listen = "127.0.0.1:${base}92"
round_ms = 250
checkpoint_cadence_rounds = 1
mldsa_secret_key_path = "${repo_root}/target/devnet/v${i}/mldsa.sk"
bls_secret_key_path = "${repo_root}/target/devnet/v${i}/bls.sk"
genesis_manifest_path = "${repo_root}/target/devnet/genesis.toml"
event_log_path = "${repo_root}/target/devnet/v${i}/events.ndjson"

# Track-B (B1) hardening defaults — overridable per-deployment.
max_client_connections = 256
client_idle_timeout_ms = 30000
client_per_ip_limit = 8

EOF
      for j in 0 1 2 3; do
        if [ "$j" != "$i" ]; then
          peer_base=9${j}
          cat >> "target/devnet/v${i}/node.toml" <<EOF
[[peers]]
id = "v${j}"
addr = "127.0.0.1:${peer_base}90"
EOF
        fi
      done
    done
    echo
    echo "==> starting 4 gsx-node processes (logs under target/devnet/v*.log)..."
    for i in 0 1 2 3; do
      logfile="target/devnet/v${i}.log"
      pidfile="target/devnet/v${i}.pid"
      # Reuse if alive; otherwise start fresh.
      if [ -f "$pidfile" ] && kill -0 "$(cat "$pidfile")" 2>/dev/null; then
        echo "    v${i} already running (pid $(cat "$pidfile"))"
      else
        nohup ./target/release/gsx-node --config "target/devnet/v${i}/node.toml" \
          > "$logfile" 2>&1 &
        echo $! > "$pidfile"
        echo "    v${i}: pid $(cat "$pidfile"), log $logfile"
      fi
    done
    echo
    echo "==> waiting for v0 to report a healthy JSON-RPC..."
    for _ in $(seq 1 30); do
      if curl -sfX POST http://127.0.0.1:9092 \
           -H 'content-type: application/json' \
           -d '{"jsonrpc":"2.0","id":1,"method":"gsx_getEpoch","params":null}' \
           > /dev/null 2>&1; then
        echo "    v0 JSON-RPC live at http://127.0.0.1:9092"
        break
      fi
      sleep 2
    done
    echo
    echo "Cluster up. Quickstart:"
    echo "  ./scripts/devnet-local.sh curl              # sanity check"
    echo "  ./scripts/devnet-local.sh faucet            # start the faucet (foreground)"
    echo "  ./scripts/devnet-local.sh logs-baremetal    # tail v0.log"
    echo "  ./scripts/devnet-local.sh down-baremetal    # stop"
    ;;

  down-baremetal)
    for i in 0 1 2 3; do
      pidfile="target/devnet/v${i}.pid"
      if [ -f "$pidfile" ]; then
        pid=$(cat "$pidfile")
        if kill -0 "$pid" 2>/dev/null; then
          kill "$pid" || true
          echo "    stopped v${i} (pid $pid)"
        else
          echo "    v${i} pidfile stale (pid $pid not running)"
        fi
        rm -f "$pidfile"
      fi
    done
    ;;

  logs-baremetal)
    tail -F target/devnet/v0.log
    ;;

  faucet)
    if [ ! -f target/devnet/faucet/mldsa.sk ]; then
      echo "error: target/devnet/faucet/mldsa.sk not found." >&2
      echo "       Run ./scripts/devnet-local.sh up first." >&2
      exit 2
    fi
    echo "==> building gsx-faucet..."
    cargo build --release -p gsx-faucet
    network_id=$(awk -F'"' '/^network_id = / { print $2; exit }' target/devnet/genesis.toml)
    faucet_addr=$(cat target/devnet/faucet/address.hex)
    echo
    echo "==> starting faucet on 127.0.0.1:8080"
    echo "    network_id     = ${network_id}"
    echo "    faucet address = ${faucet_addr}"
    echo "    rpc            = http://127.0.0.1:9092"
    echo
    exec ./target/release/gsx-faucet \
      --rpc-url http://127.0.0.1:9092 \
      --secret-key-path target/devnet/faucet/mldsa.sk \
      --public-key-path target/devnet/faucet/mldsa.pk \
      --network-id "${network_id}" \
      --bind 127.0.0.1:8080
    ;;

  *)
    echo "usage: $0 {up|up-baremetal|down|down-baremetal|reset|logs|logs-baremetal|curl|faucet}" >&2
    exit 2
    ;;
esac
