#!/usr/bin/env python3
"""
Validate the SUWP TGE allocation ledger and emit the mainnet genesis
[[prebalances]] fragment.

The ledger (allocations.toml, same directory) is the published pre-mine:
100% of the fixed SUWP supply minted at genesis into open-distribution
pools — the fair-launch model in docs/whitepaper/TOKENOMICS.md.

Checks enforced (all fatal):
  * every pool address == "0x" + BLAKE3(domain_tag)[:20].hex()
    (the chain's reserved-address scheme,
    crates/suwappu-execution/src/reserved.rs — leading 20 bytes of
    BLAKE3 of a pinned domain tag);
  * pool amounts sum to EXACTLY total_supply_suwappu;
  * no duplicate domain tags or addresses;
  * every amount is a positive integer.

Modes:
  --check        validate only, print a summary, exit non-zero on any failure
  (default)      validate, then write prebalances-tge.toml (a genesis.toml
                 [[prebalances]] fragment) to --out

Requires `blake3` (pip install blake3) or `b3sum` on PATH — same
dependency and same canonical derivation as scripts/testnet/gen-genesis.py.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path

HERE = Path(__file__).resolve().parent


def blake3_digest(data: bytes) -> bytes:
    try:
        import blake3  # type: ignore

        return blake3.blake3(data).digest()
    except ImportError:
        b3sum = shutil.which("b3sum")
        if b3sum is None:
            sys.exit(
                "ERROR: reserved-address derivation requires blake3. "
                "Install with `pip install blake3` or put `b3sum` on PATH."
            )
        out = subprocess.run([b3sum, "--no-names"], input=data, capture_output=True, check=True)
        return bytes.fromhex(out.stdout.decode().strip())


def reserved_address(domain_tag: str) -> str:
    """Leading 20 bytes of BLAKE3(domain_tag), 0x-prefixed hex — must
    byte-match suwappu_execution::reserved::reserved_address."""
    return "0x" + blake3_digest(domain_tag.encode())[:20].hex()


def load_ledger(path: Path) -> dict:
    with path.open("rb") as f:
        return tomllib.load(f)


def validate(ledger: dict) -> list[str]:
    errors: list[str] = []
    total = ledger.get("total_supply_suwappu")
    pools = ledger.get("pools", [])
    if not isinstance(total, int) or total <= 0:
        errors.append("total_supply_suwappu must be a positive integer")
        return errors
    if not pools:
        errors.append("no [[pools]] entries")
        return errors

    seen_tags: set[str] = set()
    seen_addrs: set[str] = set()
    for pool in pools:
        name = pool.get("name", "<unnamed>")
        tag = pool.get("domain_tag", "")
        addr = pool.get("address", "")
        amount = pool.get("amount_suwappu")

        if not isinstance(amount, int) or amount <= 0:
            errors.append(f"{name}: amount_suwappu must be a positive integer")
        if tag in seen_tags:
            errors.append(f"{name}: duplicate domain_tag {tag!r}")
        seen_tags.add(tag)
        if addr in seen_addrs:
            errors.append(f"{name}: duplicate address {addr}")
        seen_addrs.add(addr)

        expected = reserved_address(tag)
        if addr != expected:
            errors.append(
                f"{name}: address {addr} does not match BLAKE3({tag!r})[:20] = {expected}"
            )

    allocated = sum(p.get("amount_suwappu", 0) for p in pools)
    if allocated != total:
        errors.append(
            f"pool amounts sum to {allocated:,}, expected exactly {total:,} "
            f"(diff {allocated - total:+,})"
        )
    return errors


def emit_prebalances(ledger: dict, out: Path) -> None:
    with out.open("w") as f:
        f.write("# SUWP mainnet genesis pre-balances — generated by\n")
        f.write("# scripts/tge/gen-tge-prebalances.py from allocations.toml.\n")
        f.write("# Paste/include into the mainnet genesis.toml. Field names match\n")
        f.write("# crates/suwappu-node/src/config.rs GenesisPrebalance.\n\n")
        for pool in ledger["pools"]:
            f.write("[[prebalances]]\n")
            f.write(f'address = "{pool["address"]}"\n')
            f.write(f"balance_suwappu = {pool['amount_suwappu']}\n")
            f.write(f'role = "{pool["name"]}"\n\n')


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ledger", type=Path, default=HERE / "allocations.toml")
    ap.add_argument("--out", type=Path, default=HERE / "prebalances-tge.toml")
    ap.add_argument("--check", action="store_true", help="validate only, write nothing")
    args = ap.parse_args()

    ledger = load_ledger(args.ledger)
    errors = validate(ledger)

    total = ledger.get("total_supply_suwappu", 0)
    for pool in ledger.get("pools", []):
        pct = 100.0 * pool["amount_suwappu"] / total if total else 0.0
        print(
            f"  {pool['name']:<22} {pool['amount_suwappu']:>15,} SUWP "
            f"({pct:5.2f}%)  {pool['address']}",
            file=sys.stderr,
        )
    print(f"  {'TOTAL':<22} {total:>15,} SUWP (fixed supply)", file=sys.stderr)

    if errors:
        for e in errors:
            print(f"FAIL: {e}", file=sys.stderr)
        return 1

    print("OK: addresses match domain tags; allocations sum exactly to supply.", file=sys.stderr)
    if not args.check:
        emit_prebalances(ledger, args.out)
        print(f"wrote {args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
