#!/usr/bin/env bash
# Render per-region node.toml files using the EIPs from `terraform output`.
# Run after `terraform apply`; writes one node.toml per region under
# target/perf/configs/<region>/node.toml.
#
# Usage: scripts/perf/render-configs.sh [--consensus-port 9090] [--client-port 9091]
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TF="$ROOT/terraform/perf"
OUT="$ROOT/target/perf/configs"
CONSENSUS_PORT="${CONSENSUS_PORT:-9090}"
CLIENT_PORT="${CLIENT_PORT:-9091}"
ROUND_MS="${ROUND_MS:-100}"

if ! command -v jq >/dev/null 2>&1; then
  echo "error: jq required" >&2
  exit 1
fi

cd "$TF"
VALIDATORS_JSON="$(terraform output -json validators)"

mkdir -p "$OUT"

regions=$(echo "$VALIDATORS_JSON" | jq -r 'keys[]')
for region in $regions; do
  authority_id=$(echo "$VALIDATORS_JSON" | jq -r --arg r "$region" '.[$r].authority_id')
  public_ip=$(echo "$VALIDATORS_JSON" | jq -r --arg r "$region" '.[$r].public_ip')
  region_dir="$OUT/$region"
  mkdir -p "$region_dir"

  cfg="$region_dir/node.toml"
  {
    echo "# Auto-generated by scripts/perf/render-configs.sh. Do not edit by hand."
    echo "self_id = \"$region\""
    echo "authority_id = $authority_id"
    echo "listen = \"0.0.0.0:$CONSENSUS_PORT\""
    echo "client_listen = \"0.0.0.0:$CLIENT_PORT\""
    echo "round_ms = $ROUND_MS"
    echo "checkpoint_cadence_rounds = 1"
    echo "mldsa_secret_key_path = \"/var/lib/gsx/mldsa.sk\""
    echo "bls_secret_key_path = \"/var/lib/gsx/bls.sk\""
    echo "genesis_manifest_path = \"/etc/gsx/genesis.toml\""
    echo "event_log_path = \"/var/log/gsx/events.ndjson\""
    echo ""

    # Peer list = every region except this one.
    for peer in $regions; do
      if [ "$peer" = "$region" ]; then continue; fi
      peer_ip=$(echo "$VALIDATORS_JSON" | jq -r --arg r "$peer" '.[$r].public_ip')
      echo "[[peers]]"
      echo "id = \"$peer\""
      echo "addr = \"$peer_ip:$CONSENSUS_PORT\""
      echo ""
    done
  } > "$cfg"
  echo "wrote $cfg"
done
